service: wordcloud-api

provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1
  stage: production

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    usePipenv: true
    dockerizePip: true
    layer: true

package:
  exclude:
    - node_modules/**
    - docs/**
    - dockers/**
    - tmp/**
    - .git/**
    - .gitignore
    - package.json
    - README.md
    - server.py
    - swagger.yml
    - yarn.lock
    - yarn-error.lock
    - .env.sample
    - .DS_Store
    - npm-debug.log
    - .serverless/**
    - .serverless_plugins/**

functions:
  wordcloud:
    handler: src/handler.wc_generate
    memorySize: 128
    timeout: 900
    layers:
      - {Ref: FontsLambdaLayer}
    events:
      - http:
          method: get
          path: wordcloud/generate
      - http:
          method: post
          path: wordcloud/generate

layers:
  fonts:
    path: fonts